# fly.toml app configuration file generated for scythebutler on 2026-02-14T13:48:15Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'scythebutler'
primary_region = 'iad'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
