name: Set Discord Token on Fly.io

on:
  workflow_dispatch:  # allows manual trigger

jobs:
  set-token:
    runs-on: ubuntu-latest

    steps:
      - name: Install Flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Login to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}  # Fly.io token secret
        run: flyctl auth token $FLY_API_TOKEN

      - name: Set Discord Token
        run: flyctl secrets set DISCORD_TOKEN=${{ secrets.DISCORDTOKEN }} -a scythebutler
