name: Push Discord Token to Fly.io

on:
  workflow_dispatch:

jobs:
  push-token:
    runs-on: ubuntu-latest

    steps:
      - name: Install Flyctl and Set PATH
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH
        shell: bash

      - name: Verify flyctl
        run: flyctl version
        shell: bash

      - name: Log GitHub Secrets
        run: |
          echo "DISCORDTOKEN set? -> ${{ secrets.DISCORDTOKEN != '' }}"
          echo "FLY_API_TOKEN set? -> ${{ secrets.FLY_API_TOKEN != '' }}"
        shell: bash

      - name: Login to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl auth token $FLY_API_TOKEN
        shell: bash

      - name: Set Discord Token
        run: flyctl secrets set DISCORD_TOKEN=${{ secrets.DISCORDTOKEN }} -a scythebutler --no-interactive
        shell: bash
